import { SALT_LAKE_COUNTY_CITIES, UTAH_COUNTY_CITIES } from "@/lib/constants";

export type CityPageData = {
  name: string;
  slug: string;
  county: "Utah County" | "Salt Lake County";
  setting: string;
  design: string;
  areas: string[];
  pricing: string;
  nearby: string[];
  faqFocus: "hoa" | "snow" | "historic" | "commercial" | "wind";
};

const city = (
  name: string,
  county: CityPageData["county"],
  setting: string,
  design: string,
  areas: string[],
  pricing: string,
  nearby: string[],
  faqFocus: CityPageData["faqFocus"],
): CityPageData => ({
  name,
  slug: `${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}-ut`,
  county,
  setting,
  design,
  areas,
  pricing,
  nearby,
  faqFocus,
});

export const CITY_PAGES: CityPageData[] = [
  city("Highland", "Utah County", "Highland combines foothill exposure, broad residential lots, and substantial custom homes. Rooflines often include tall peaks, multiple gables, and long garage runs, while open views toward the mountains make clean spacing especially noticeable after dark.", "Displays here often benefit from a strong roofline outline with restrained accents on columns, entry peaks, or mature trees. We plan access carefully on sloped lots and account for wind and early winter weather near the bench.", ["Highland Glen", "Beacon Hills", "the Alpine Highway corridor"], "Larger rooflines and mature-tree accents are common variables in Highland quotes, so linear footage, height, and safe access usually matter more than lot size alone.", ["alpine-ut", "american-fork-ut", "lehi-ut"], "snow"),
  city("Alpine", "Utah County", "Alpine sits tight against the Wasatch foothills, where custom homes, mature landscaping, and mountain weather shape holiday-lighting plans. Many properties have pronounced roof peaks, deeper setbacks, and trees that can support a layered display visible from winding neighborhood streets.", "We favor designs that follow the architecture instead of overwhelming it: crisp C9 rooflines, selected peaks, and carefully wrapped trunks or evergreens. Elevation, snow, and roof access receive extra attention when installation dates are scheduled.", ["Alpine Cove", "Fort Canyon", "the city center near Main Street"], "Alpine projects often involve taller architecture or tree work, so estimates reflect roof access, total lighted footage, and the number and size of landscape features selected.", ["highland-ut", "lehi-ut", "american-fork-ut"], "snow"),
  city("Pleasant Grove", "Utah County", "Pleasant Grove has an unusually broad mix of established neighborhoods, newer foothill homes, and active commercial corridors. A single street can include simple rambler rooflines, two-story gables, mature shade trees, and newer infill, so useful lighting plans need to respond to the individual property.", "Classic warm-white rooflines work well across the city, with peaks, porches, and tree accents added where they improve visibility. On foothill properties we also account for grade, access, and changing winter conditions.", ["Manila", "the downtown area", "neighborhoods below Battle Creek"], "Pleasant Grove pricing ranges from straightforward single-story outlines to taller, multi-peak homes; the quote is based on measured coverage, access, trees, and design complexity.", ["lindon-ut", "cedar-hills-ut", "american-fork-ut"], "historic"),
  city("Lehi", "Utah County", "Lehi’s rapid growth has created a mix of established streets, master-planned neighborhoods, townhomes, and large commercial destinations. Homes near the foothills can have tall, multi-gable rooflines, while west-side communities often feature newer two-story plans and more open exposure to wind.", "A balanced Lehi display may trace the main roofline, highlight an entry peak, and add a tree or porch accent without competing with neighboring homes. We coordinate installation details with HOA expectations when applicable and plan access around compact lots and shared streets.", ["Traverse Mountain", "Thanksgiving Point", "Holbrook Farms"], "Common Lehi projects include two-story front elevations and several connected peaks. Height, total linear footage, access, and optional tree or garage accents determine the project price.", ["american-fork-ut", "highland-ut", "saratoga-springs-ut", "bluffdale-ut"], "hoa"),
  city("American Fork", "Utah County", "American Fork includes mature neighborhoods near its historic center, newer subdivisions toward the edges of the city, and busy retail areas near I-15. That variety produces everything from compact single-story rooflines to broad two-story elevations with several peaks and garage bays.", "We design around the home’s most visible architectural lines, then add porch, column, or tree accents where they create depth. Mature landscaping and narrow side-yard access are considered before ladders and installation equipment arrive.", ["Historic Main Street", "Art Dye Park", "the I-15 retail corridor"], "American Fork quotes vary mainly with roof height and measured coverage. Established homes may add mature-tree work, while newer homes often involve multiple front-facing gables.", ["lehi-ut", "pleasant-grove-ut", "highland-ut", "lindon-ut"], "historic"),
  city("Saratoga Springs", "Utah County", "Saratoga Springs is shaped by newer residential communities, Utah Lake views, and open western exposure. Many homes have two-story elevations and multiple front-facing gables, while lake and valley winds make secure clips and well-planned power routes particularly important.", "We usually recommend a clean architectural outline with one or two deliberate focal points, such as the entry peak or a prominent garage line. Installation planning accounts for open lots, wind, and HOA design standards where they apply.", ["TalonsCove", "Northshore", "the Crossroads area"], "Two-story access and multi-peak rooflines are common in Saratoga Springs. Estimates reflect measured footage, height, selected accents, and any trees or detached features included.", ["lehi-ut", "eagle-mountain-ut", "american-fork-ut"], "wind"),
  city("Eagle Mountain", "Utah County", "Eagle Mountain’s master-planned communities spread across open terrain with newer homes, wide skies, and frequent wind exposure. Rooflines are often highly visible from neighborhood approaches, making straight runs, consistent bulb spacing, and secure attachment central to a polished display.", "We plan displays to read clearly from the street without adding clutter to every architectural line. Main peaks, long eaves, garages, and select porch features usually provide the strongest result, with installation methods chosen for exposed conditions.", ["The Ranches", "SilverLake", "City Center"], "Eagle Mountain projects commonly involve newer two-story homes and long front elevations. Pricing follows roofline footage, working height, complexity, and optional landscaping accents.", ["lehi-ut", "american-fork-ut", "highland-ut"], "wind"),
  city("Cedar Hills", "Utah County", "Cedar Hills rises along the foothills between American Fork Canyon and the north Utah Valley communities. Sloped streets, multi-level homes, and clear valley views make roofline precision important, while elevation can bring colder and snowier installation conditions.", "Lighting plans often emphasize upper peaks and front-facing eaves that are visible downhill, then use restrained accents at entries or columns. We assess grade, ladder placement, roof pitch, and weather exposure before scheduling the work.", ["Cedar Hills Golf Club", "the Canyon Road area", "foothill neighborhoods above Cedar Hills Drive"], "Height and slope can influence Cedar Hills projects as much as linear footage. Quotes account for safe access, roof complexity, and the number of upper peaks or landscape features included.", ["pleasant-grove-ut", "highland-ut", "american-fork-ut"], "snow"),
  city("Lindon", "Utah County", "Lindon blends large residential parcels and mature trees with newer neighborhoods and business areas closer to Geneva Road and I-15. Homes can have long rooflines and generous setbacks, so displays need enough structure to remain clear from the street.", "A strong primary roofline paired with selected tree, column, or garage accents suits many Lindon properties. For larger lots, we prioritize the features that create the most visual impact rather than lighting every possible edge.", ["Lindon City Center", "the Geneva Road corridor", "foothill neighborhoods east of State Street"], "Lindon estimates often reflect longer roof runs, larger trees, or detached features. We price the measured design and access requirements rather than using a flat city-wide package.", ["pleasant-grove-ut", "orem-ut", "american-fork-ut"], "commercial"),
  city("Orem", "Utah County", "Orem’s residential grid includes mid-century ramblers, split-level homes, newer infill, apartments, and foothill properties with broader views. Mature trees are common in established areas, while State Street and University Parkway add prominent commercial lighting opportunities.", "We adapt the display to the building: simple eave lines can make a classic older home feel finished, while taller or remodeled homes may benefit from peaks and entry accents. Tree work is planned around branch structure and visibility from the street.", ["Scera Park", "the University Place area", "Orchard neighborhoods near the foothills"], "Orem pricing can range from accessible single-story rooflines to complex two-story homes and mature trees. Footage, height, tree size, and commercial versus residential scope drive the estimate.", ["lindon-ut", "provo-ut", "vineyard-ut", "pleasant-grove-ut"], "commercial"),
  city("Provo", "Utah County", "Provo combines historic neighborhoods, compact bungalows, student-oriented housing, foothill homes, and a walkable downtown business district. Roof materials, setbacks, and architecture change quickly across the city, so a useful lighting design starts with the actual structure rather than a generic package.", "Historic homes often look best with a clean eave outline and porch details, while east-bench properties may call for taller access and selected peaks. Downtown and mixed-use projects require careful timing, power planning, and pedestrian awareness.", ["Downtown Provo", "Joaquin", "the Riverbottoms"], "Provo quotes reflect the property type: compact rooflines can stay simple, while hillside homes, mature trees, and storefront displays add height, access, or scheduling considerations.", ["spanish-fork-ut", "american-fork-ut", "lehi-ut"], "historic"),
  city("Springville", "Utah County", "Springville stretches from an established central grid toward newer neighborhoods near the foothills and west side. Older homes, mature trees, newer two-story plans, and canyon-influenced weather create varied installation conditions within a relatively compact area.", "We use the architecture to set the display’s rhythm, outlining the roof edge and adding peaks, porches, or trees only where they strengthen the view. East-side grade and wind are considered along with access around older landscaping.", ["Historic Main Street", "Hobble Creek", "the west-side neighborhoods near I-15"], "Springville pricing depends on measured roofline coverage, story height, trees, and design complexity. Older single-story homes and newer multi-gable homes naturally produce different scopes.", ["provo-ut", "mapleton-ut", "spanish-fork-ut"], "historic"),
  city("Spanish Fork", "Utah County", "Spanish Fork includes a traditional town center, broad suburban neighborhoods, newer growth, and properties near the canyon and open south-valley edges. Homes range from simple ranch forms to tall multi-peak elevations, with wind exposure varying by location.", "Most displays begin with a crisp front roofline, then add a central peak, porch, or garage run for balance. We plan clips, power, and installation timing around the roof material, access, and local weather exposure.", ["Historic Main Street", "Canyon Creek", "the Spanish Fork River area"], "Spanish Fork estimates are shaped by roofline length, building height, number of peaks, and optional trees or detached features. Larger lots do not automatically mean a larger display.", ["payson-ut", "provo-ut", "american-fork-ut"], "wind"),
  city("Mapleton", "Utah County", "Mapleton is known for foothill views, larger residential lots, and a blend of established rural character with newer custom homes. Long setbacks, tall roof peaks, and substantial trees can make scale and visibility central to a successful holiday display.", "We identify the architectural lines visible from the road and build a focused design around them. Main eaves, entry peaks, and one or two landscape features often create a stronger result than spreading lights thinly across a large property.", ["Mapleton City Center", "Maple Canyon", "the east bench"], "Mapleton projects may include longer roof runs, custom architecture, or large trees. Pricing is based on the selected visible features, measured footage, height, and installation access.", ["springville-ut", "spanish-fork-ut", "salem-ut"], "snow"),
  city("Payson", "Utah County", "Payson combines an established central city with expanding neighborhoods near the freeway and the south valley’s open edges. Housing ranges from modest single-story homes to newer two-story plans, and mature trees remain a defining feature in older blocks.", "A classic eave outline works well on many Payson homes, with porch, peak, or tree accents added to suit the façade. We also consider wind exposure and practical ladder access around fences, side yards, and landscaping.", ["Historic Downtown", "Memorial Park", "the I-15 growth area"], "Payson estimates commonly vary by story height, total roofline length, and mature-tree work. We measure the requested design so homeowners can prioritize the features that matter most.", ["spanish-fork-ut", "provo-ut", "american-fork-ut"], "historic"),
  city("Santaquin", "Utah County", "Santaquin sits at the southern end of Utah Valley where open terrain, bench neighborhoods, and changing elevation can expose homes to wind and early winter weather. Newer subdivisions mix with established streets and properties with wider setbacks.", "Displays are designed for secure, consistent roofline coverage and clear visibility from the street. We evaluate upper peaks, roof pitch, power locations, and exposed elevations before choosing installation timing and access methods.", ["Summit Ridge", "the Main Street area", "bench neighborhoods along the east side"], "Santaquin quotes account for measured footage, two-story access, wind-exposed peaks, and optional tree or porch accents. Each scope is built around the actual home.", ["payson-ut", "salem-ut", "elk-ridge-ut"], "wind"),
  city("Salem", "Utah County", "Salem’s residential character includes established streets near the city center, homes around the pond area, larger lots, and newer neighborhoods toward the city edges. Open views and generous setbacks often favor a clear, well-proportioned display.", "We start with the roofline that is most visible from the approach, then select peaks, porches, garages, or trees that add depth. Larger yards are planned around sightlines so the display still feels connected to the home.", ["Salem Pond", "the city center", "newer neighborhoods toward Woodland Hills Drive"], "Salem pricing reflects selected roofline footage, height, tree size, and access. A broad lot can still have a focused project if only the most visible architectural features are included.", ["payson-ut", "spanish-fork-ut", "mapleton-ut", "elk-ridge-ut"], "hoa"),
  city("Vineyard", "Utah County", "Vineyard is one of Utah Valley’s newest high-density communities, with townhomes, apartments, compact detached homes, and lake-adjacent development. Shared façades, smaller lots, HOA rules, and west-side wind all affect what can be installed and where.", "We confirm ownership boundaries and HOA requirements before proposing lights on attached or closely spaced properties. Clean entry, eave, balcony, and garage accents can create a festive result without crowding a compact elevation.", ["Vineyard Connector", "Grove Park", "Utah Lake shoreline neighborhoods"], "Vineyard estimates are often driven by access and approval requirements rather than sheer footage. Attached housing, upper floors, and shared rooflines need a clearly defined scope.", ["orem-ut", "lindon-ut", "provo-ut"], "hoa"),
  city("Elk Ridge", "Utah County", "Elk Ridge’s hillside setting creates elevated views, sloped streets, and homes with prominent rooflines. Winter conditions can arrive earlier than on the valley floor, and grade can make access planning a significant part of the installation.", "We emphasize front-facing lines and peaks that remain visible across the slope, then add entry or tree accents selectively. Roof pitch, driveway grade, ladder position, and weather windows are reviewed before installation.", ["the Loafer Mountain foothills", "Park Drive", "the Salem Hills side of the city"], "Elk Ridge pricing accounts for working height, slope, roof complexity, and selected footage. Access conditions can affect labor even when the lighted roofline is relatively compact.", ["payson-ut", "salem-ut", "woodland-hills-ut"], "snow"),
  city("Woodland Hills", "Utah County", "Woodland Hills occupies a wooded foothill setting above south Utah Valley, with larger custom homes, steep grades, and mature trees. Elevation and mountain weather make early planning valuable, while long approaches reward displays with strong, readable lines.", "We select roof edges and peaks that can be seen through the landscape and avoid overloading already detailed architecture. Tree choices, roof access, grade, snow, and wind all influence the final design and schedule.", ["Woodland Hills Drive", "Oakwood Drive", "the foothills above Salem"], "Woodland Hills projects often involve custom rooflines, grade, or substantial trees. Estimates reflect the selected design, access equipment, working height, and weather-sensitive scheduling.", ["elk-ridge-ut", "salem-ut", "mapleton-ut"], "snow"),
  city("Salt Lake City", "Salt Lake County", "Salt Lake City includes historic avenues, compact bungalows, modern infill, hillside homes, apartments, and major commercial districts. Rooflines and access vary sharply between neighborhoods, and mature street trees or limited parking can shape installation logistics.", "We tailor residential displays to the architecture, from simple porch and eave lines on older homes to selected peaks on newer builds. Commercial work is planned around operating hours, pedestrian routes, power, and visibility.", ["The Avenues", "Sugar House", "Downtown Salt Lake City"], "Salt Lake City pricing reflects property type, access, height, parking constraints, tree work, and commercial scheduling. Compact homes can be simple, while hillside or downtown projects require more planning.", ["murray-ut", "sandy-ut", "riverton-ut"], "commercial"),
  city("West Valley City", "Salt Lake County", "West Valley City spans established residential streets, newer western neighborhoods, major employment areas, and busy commercial corridors. Home styles range from accessible ramblers to larger two-story elevations, often with broad garage-facing rooflines.", "A clean main eave and garage outline can create strong street presence, with peaks, porches, or trees added where appropriate. We plan around fences, mature landscaping, and open west-side weather exposure.", ["Hunter", "Granger", "the Valley Fair area"], "West Valley City estimates vary with building height, roofline footage, selected accents, and access. Commercial façades and larger two-story homes receive property-specific scopes.", ["kearns-ut", "taylorsville-ut", "magna-ut", "south-salt-lake-ut"], "commercial"),
  city("West Jordan", "Salt Lake County", "West Jordan combines established east-side neighborhoods, newer western growth, and large retail areas. Homes often present long garage lines, multiple front gables, and a mix of mature and newly planted landscaping.", "We use those visible roof elements to build a balanced outline and can add entry, column, or tree accents where they improve depth. HOA expectations and west-side wind are reviewed when relevant.", ["Jordan Landing", "Copper Hills", "the Gardner Village area"], "West Jordan pricing commonly follows front-elevation length, upper-story access, number of peaks, and optional landscaping. Retail or HOA projects are scoped around operating and approval requirements.", ["south-jordan-ut", "taylorsville-ut", "kearns-ut", "riverton-ut"], "hoa"),
  city("South Jordan", "Salt Lake County", "South Jordan includes established neighborhoods east of Bangerter Highway, master-planned communities around Daybreak, and growing retail and office districts. Architecture ranges from traditional suburban homes to compact townhomes with shared design standards.", "We coordinate with HOA rules where required and focus on crisp, repeatable roofline patterns that complement nearby homes. Open areas can be windy, so secure attachment and practical power routing matter throughout the season.", ["Daybreak", "River Heights", "the District"], "South Jordan estimates reflect roofline footage, story height, HOA-approved scope, and chosen landscape accents. Townhomes and large detached homes require different access and ownership checks.", ["riverton-ut", "west-jordan-ut", "herriman-ut", "sandy-ut"], "hoa"),
  city("Riverton", "Salt Lake County", "Riverton blends older properties with larger lots, mature landscaping, and fast-growing subdivisions with multi-gable two-story homes. Wide front elevations and open southwest valley exposure make proportion and attachment quality important.", "We usually define the primary eaves and peaks first, then add porch, garage, or tree accents to match the home’s scale. Lot access, fencing, and any HOA standards are considered during the quote.", ["Riverton City Park", "Western Springs", "the Mountain View Village area"], "Riverton project prices are shaped by long roof runs, second-story peaks, mature trees, and selected coverage. The estimate separates must-have features from optional accents.", ["bluffdale-ut", "draper-ut", "sandy-ut", "murray-ut"], "hoa"),
  city("Draper", "Salt Lake County", "Draper stretches from established valley neighborhoods to steep foothill communities with expansive views. Homes may have complex custom rooflines, significant grade, and exposure to canyon winds or heavier bench snow, while the city’s commercial areas need high-visibility designs.", "We plan around slope and architecture, selecting roof edges and peaks that can be installed safely and read clearly from below. Foothill projects are scheduled with access and weather in mind, and HOA requirements are confirmed when applicable.", ["SunCrest", "Corner Canyon", "Draper Historic Park"], "Draper quotes often reflect height, roof pitch, grade, custom architecture, and wind exposure. Commercial and foothill properties receive a measured, access-specific plan.", ["sandy-ut", "bluffdale-ut", "riverton-ut", "lehi-ut"], "snow"),
  city("Sandy", "Salt Lake County", "Sandy rises from established valley-floor neighborhoods toward the Wasatch bench, creating a broad range of homes and winter conditions. Ramblers with mature trees sit alongside taller foothill properties with steep rooflines and canyon weather exposure.", "We match the display to the elevation: classic eave and porch lines suit many central neighborhoods, while bench homes often call for carefully selected peaks and weather-aware access. Trees are chosen for visibility and branch structure.", ["Historic Sandy", "Willow Creek", "the Little Cottonwood corridor"], "Sandy pricing varies with story height, roof pitch, tree size, grade, and selected footage. Foothill access can influence labor beyond the visible size of the display.", ["draper-ut", "cottonwood-heights-ut", "midvale-ut", "murray-ut"], "snow"),
  city("Murray", "Salt Lake County", "Murray’s central location includes mature residential streets, mid-century homes, newer redevelopment, and major medical and commercial properties. Established trees and compact side yards can be as important to installation planning as the roofline itself.", "Simple, even eave outlines complement many Murray homes, with porch, chimney, or tree accents used selectively. For business properties, we consider customer access, signage visibility, and installation timing.", ["Murray Park", "Murray Downtown", "the Fashion Place area"], "Murray estimates range from accessible single-story homes to mature-tree and commercial projects. Footage, access, tree size, and operating-hour constraints determine the scope.", ["salt-lake-city-ut", "sandy-ut", "riverton-ut", "draper-ut"], "commercial"),
  city("Midvale", "Salt Lake County", "Midvale combines older compact neighborhoods with newer mixed-use development and busy commercial corridors. Smaller lots, mature trees, attached housing, and redeveloped properties create different access and approval needs within a short distance.", "We keep residential designs proportionate to the façade, often emphasizing eaves, porches, and a central peak. Attached properties require clear ownership or HOA approval, while commercial work is coordinated around customers and signage.", ["Historic Midvale", "Bingham Junction", "the Fort Union area"], "Midvale pricing reflects roofline length, working height, shared-building considerations, tree work, and commercial access. Each quote defines exactly which elevations are included.", ["murray-ut", "sandy-ut", "west-jordan-ut", "cottonwood-heights-ut"], "historic"),
  city("Taylorsville", "Salt Lake County", "Taylorsville is largely defined by established suburban neighborhoods, mature landscaping, accessible rambler and split-level rooflines, and central valley commercial areas. Many homes offer excellent street visibility without requiring an oversized display.", "A continuous front eave, garage line, and one focused entry or tree accent often provides the right balance. We inspect mature trees, side-yard access, and roof transitions before finalizing the layout.", ["Valley Regional Park", "Bennion", "the Redwood Road corridor"], "Taylorsville estimates commonly depend on roofline footage, split-level transitions, tree size, and selected accents. Many projects can be kept focused on the visible front elevation.", ["west-jordan-ut", "murray-ut", "west-valley-city-ut", "kearns-ut"], "historic"),
  city("Herriman", "Salt Lake County", "Herriman’s newer master-planned neighborhoods climb from open southwest valley terrain toward the foothills. Multi-story homes, layered front gables, HOA standards, wind, and elevation all influence how a holiday display should be designed and installed.", "We emphasize the main architectural hierarchy instead of outlining every edge, using the strongest eaves and peaks to create a clean view. Secure clips, power planning, grade, and community guidelines are reviewed before installation.", ["Rosecrest", "Juniper Point", "Herriman Towne Center"], "Herriman pricing often reflects upper-story access, multiple peaks, longer front elevations, and foothill grade. HOA-approved options can be separated into base and accent choices.", ["riverton-ut", "south-jordan-ut", "bluffdale-ut", "west-jordan-ut"], "hoa"),
  city("Bluffdale", "Salt Lake County", "Bluffdale mixes acreage and equestrian-scale properties with rapidly growing subdivisions near the Salt Lake and Utah County line. Larger setbacks, open wind exposure, and broad custom or newer rooflines make visibility and access central design questions.", "We focus light where it will read from the road: main roof edges, entry peaks, garages, and a limited number of landscape features. Long driveways, fences, grade, and power locations are part of the installation plan.", ["Independence at the Point", "Vintage Park", "the Jordan Narrows area"], "Bluffdale estimates may include long roof runs, detached structures, or larger trees, but pricing remains tied to the selected coverage, height, and access rather than acreage.", ["draper-ut", "riverton-ut", "herriman-ut", "lehi-ut"], "wind"),
  city("Cottonwood Heights", "Salt Lake County", "Cottonwood Heights sits beneath the Cottonwood canyons, where hillside lots, mature trees, and mountain weather shape holiday-lighting work. Homes range from established brick properties to remodeled and custom foothill residences with steep or multi-level rooflines.", "We choose lines that remain visible on sloped sites and plan around trees, roof pitch, driveway grade, and faster-changing weather. Earlier installation windows can reduce conflicts with snow and icy access.", ["Old Mill", "Butler", "the Bengal Boulevard area"], "Cottonwood Heights pricing reflects roof pitch, grade, height, mature trees, and the selected visible elevations. Foothill access can require more time than similar footage on a level lot.", ["sandy-ut", "holladay-ut", "millcreek-ut", "midvale-ut"], "snow"),
  city("Holladay", "Salt Lake County", "Holladay is characterized by mature trees, established homes, larger lots in some areas, and a village-scale commercial center. Older roof forms, remodeled properties, and dense landscaping create opportunities for warm, layered displays with a restrained feel.", "We often pair a crisp home outline with one carefully selected tree, entry, or column feature. Mature branches, hidden power routes, narrow access, and the home’s existing architecture guide the design.", ["Holladay Village", "Olympus Hills", "Walker Lane"], "Holladay estimates commonly involve mature-tree work, custom roof transitions, or long setbacks. Pricing follows the actual features selected, their height, and installation access.", ["cottonwood-heights-ut", "millcreek-ut", "murray-ut"], "historic"),
  city("Millcreek", "Salt Lake County", "Millcreek runs from central valley neighborhoods to the Wasatch bench, with older brick homes, modern rebuilds, mature trees, and canyon-influenced weather. Grade and roof complexity can change significantly from west to east.", "Straight eave lines and porch accents work well on many established homes, while bench properties may need selected upper peaks and more careful access planning. We consider trees, slope, wind, and winter timing before installation.", ["East Millcreek", "Canyon Rim", "Millcreek Common"], "Millcreek pricing varies with story height, roof pitch, grade, mature trees, and selected coverage. Bench projects often require more access planning than valley-floor homes.", ["holladay-ut", "south-salt-lake-ut", "salt-lake-city-ut", "murray-ut"], "snow"),
  city("Magna", "Salt Lake County", "Magna pairs an established historic grid and modest residential rooflines with newer growth toward the west. Open valley exposure can bring wind, while older properties may have mature trees, varied additions, and practical access constraints.", "We create clean front-facing outlines that suit the home’s scale, then add a porch, garage, or tree accent where it improves the view. Attachment and power routing are planned for exposed conditions and existing architecture.", ["Historic Magna Main Street", "Pleasant Green", "the 8000 West growth area"], "Magna quotes are based on roofline footage, height, additions, trees, and selected accents. Straightforward single-story projects can remain focused and efficient.", ["west-valley-city-ut", "kearns-ut", "west-jordan-ut"], "wind"),
  city("Kearns", "Salt Lake County", "Kearns has many compact, established neighborhoods with ramblers, split-level homes, mature yards, and highly visible street-facing rooflines. Those proportions often support classic displays that feel complete without excessive footage.", "A continuous eave or garage line, paired with an entry or small tree accent, can create strong curb appeal. We account for additions, fencing, landscaping, and safe side-yard access during the quote.", ["Oquirrh Park", "the Kearns Oquirrh Park Fitness Center area", "neighborhoods along 5400 South"], "Kearns pricing typically follows accessible front roofline footage, split-level transitions, story height, and optional tree work. Homeowners can prioritize a simple outline or add focused accents.", ["west-valley-city-ut", "taylorsville-ut", "west-jordan-ut", "magna-ut"], "historic"),
  city("South Salt Lake", "Salt Lake County", "South Salt Lake’s compact footprint includes older homes, small lots, apartments, creative businesses, and commercial or industrial frontage. Limited staging space, shared buildings, mature street trees, and traffic can shape how installations are scheduled.", "We keep residential designs proportionate, using roof edges, porches, and entries that remain visible on compact streets. Business displays are planned around operating hours, public access, signs, and available power.", ["Central Pointe", "the Creative Industries Zone", "the State Street corridor"], "South Salt Lake estimates account for roofline footage, tight access, shared-building approvals, parking, and commercial scheduling. Smaller buildings can still need detailed logistics.", ["salt-lake-city-ut", "millcreek-ut", "murray-ut", "west-valley-city-ut"], "commercial"),
];

/**
 * Initial local-SEO launch set. Other city records stay available for future
 * research, but they are not routed, linked, or submitted for indexation.
 */
export const LAUNCH_CITY_NAMES = [
  "Provo",
  "Lehi",
  "Eagle Mountain",
  "Alpine",
  "Highland",
  "Draper",
  "Bluffdale",
  "Salt Lake City",
  "Sandy",
  "Spanish Fork",
  "Payson",
  "Murray",
  "Riverton",
  "American Fork",
] as const;

const launchCityNames = new Set<string>(LAUNCH_CITY_NAMES);

export const LAUNCH_CITY_PAGES = CITY_PAGES.filter((entry) =>
  launchCityNames.has(entry.name),
);

export const CITY_BY_SLUG = new Map(
  LAUNCH_CITY_PAGES.map((entry) => [entry.slug, entry]),
);

export function cityPagePath(entry: Pick<CityPageData, "slug">) {
  return `/christmas-light-installation/${entry.slug}`;
}

export function countyPagePath(county: CityPageData["county"]) {
  return `/service-areas/${county === "Utah County" ? "utah-county" : "salt-lake-county"}`;
}

export function getCountyCities(county: CityPageData["county"]) {
  const names = county === "Utah County" ? UTAH_COUNTY_CITIES : SALT_LAKE_COUNTY_CITIES;
  return names
    .map((name) => LAUNCH_CITY_PAGES.find((entry) => entry.name === name))
    .filter(Boolean) as CityPageData[];
}

export function getCityFaqs(entry: CityPageData) {
  const focusFaq = {
    hoa: {
      question: `Can you work with HOA lighting rules in ${entry.name}?`,
      answer: `Yes. If your ${entry.name} property has an HOA, send us the applicable lighting standards or approval requirements. We can keep the design within approved rooflines, colors, installation dates, and takedown deadlines.`,
    },
    snow: {
      question: `How do snow and elevation affect installations in ${entry.name}?`,
      answer: `We monitor roof, ladder, and driveway conditions before every ${entry.name} installation. Earlier scheduling usually provides safer access, especially on foothill streets, steep lots, and roofs that hold snow or ice.`,
    },
    historic: {
      question: `Can you install lights on older homes in ${entry.name}?`,
      answer: `Yes. We inspect the roof edge, gutters, trim, additions, and available power before choosing clips and routes. The goal is a clean display that respects the proportions and materials of the home.`,
    },
    commercial: {
      question: `Do you install commercial Christmas lights in ${entry.name}?`,
      answer: `Yes. We quote storefronts, offices, multifamily common areas, and other commercial properties in ${entry.name}. Scheduling, customer access, power, visibility, and property-manager approval are included in the plan.`,
    },
    wind: {
      question: `How do you prepare ${entry.name} displays for wind?`,
      answer: `We use commercial-grade strands and clips selected for the roof edge, then plan secure runs without loose unsupported sections. No installation is storm-proof, but careful attachment and in-season service reduce avoidable problems.`,
    },
  }[entry.faqFocus];

  return [
    {
      question: `How much does Christmas light installation cost in ${entry.name}?`,
      answer: `${entry.pricing} Seasonal installation starts at $699 in year one and $299 in later years, with every property quoted individually.`,
    },
    {
      question: `When should I schedule Christmas light installation in ${entry.name}?`,
      answer: `Earlier reservations provide the best selection of installation dates. We schedule ${entry.name} projects around crew routes, roof conditions, weather, and the design’s complexity rather than promising the same date for every property.`,
    },
    focusFaq,
    {
      question: `Do you offer both temporary and permanent lighting in ${entry.name}?`,
      answer: `Yes. Seasonal service includes the lights, installation, maintenance, takedown, and storage. Permanent architectural lighting is installed once and can be programmed for Christmas and other occasions throughout the year.`,
    },
    {
      question: `What happens if a bulb goes out during the season?`,
      answer: `Contact Chestnut & Cheer and we will arrange in-season service for normal bulb failures on the display we installed. Maintenance is included with our seasonal lighting service.`,
    },
  ];
}
