import type { Metadata } from "next";
import Image from "next/image";
import { Gift, Heart, Lightbulb, Mail, Phone, Sparkles, TreePine, UtensilsCrossed } from "lucide-react";
import { CheerForm } from "@/components/share-the-cheer/CheerForm";
import { Button } from "@/components/ui/Button";
import { JsonLd } from "@/components/seo/JsonLd";
import { ASSETS, COMPANY, LINKS } from "@/lib/constants";
import { SHARE_THE_CHEER, nominationsOpen } from "@/lib/share-the-cheer";
import { absoluteUrl } from "@/lib/site";
import { getBreadcrumbSchema, getOrganizationSchema } from "@/lib/structured-data";

const description = "Nominate a local family or join Chestnut & Cheer and other Utah businesses in creating meaningful Christmas experiences through lights, trees, meals, and community support.";
export const metadata: Metadata = {
  title: { absolute: "Share the Cheer | Supporting Utah Families at Christmas" }, description,
  alternates: { canonical: "/share-the-cheer" },
  openGraph: { title: "Share the Cheer | Supporting Utah Families at Christmas", description, url: absoluteUrl("/share-the-cheer"), type: "website", images: [{ url: absoluteUrl(ASSETS.photos.hero), alt: "Chestnut & Cheer holiday lighting at a Utah home" }] },
  twitter: { card: "summary_large_image", title: "Share the Cheer | Supporting Utah Families at Christmas", description, images: [absoluteUrl(ASSETS.photos.hero)] },
};

const selectionDate = new Intl.DateTimeFormat("en-US", { month: "long", day: "numeric", timeZone: "UTC" }).format(new Date(`${SHARE_THE_CHEER.selectionContactBy}T12:00:00Z`));

const faq = [
  ["Who can nominate a family?", "Anyone who knows a local family facing a difficult season may nominate them, provided they believe the family may be contacted privately."],
  ["Can a family nominate itself?", "Yes. A family may submit its own nomination using its own contact information."],
  ["What areas are eligible?", `Families must live within our current service area: ${COMPANY.serviceAreas.join(" and ")}. Installation also depends on property access and safety.`],
  ["When will selected families be contacted?", `We plan to contact selected families by ${selectionDate}. Timing can change as the season's plans are confirmed.`],
  ["Is every nominated family selected?", "No. We expect to serve a limited number of local families. A nomination does not guarantee selection."],
  ["What will each family receive?", "We hope to bring together Christmas dinner, a real tree, and professional outdoor lights. Specific packages depend on confirmed partners, property safety, and availability; no contribution can be guaranteed in advance."],
  ["Can a business donate something not listed?", "Absolutely. Tell us what you have in mind through the partner form, and our office will follow up."],
  ["Can individuals contribute?", "Yes. Use the partner form or contact our office, and we will help find a useful way to contribute."],
  ["Will family names or photos be published?", "Only with clear permission. Families can remain entirely private and are never required to take part in publicity."],
  ["Are financial contributions tax-deductible?", "Do not assume a contribution is tax-deductible. Please ask our office how a contribution would be handled and consult your tax adviser. We will only describe a contribution as tax-deductible if it is processed through a verified qualifying nonprofit."],
] as const;

function SectionHeading({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) {
  return <div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-primary-red">{eyebrow}</p><h2 className="mt-3 font-display text-3xl font-semibold text-chestnut sm:text-4xl">{title}</h2>{children && <p className="mt-4 leading-relaxed text-chestnut/80">{children}</p>}</div>;
}

export default function ShareTheCheerPage() {
  return <>
    <JsonLd data={[getOrganizationSchema(), getBreadcrumbSchema([{ name: "Home", path: "/" }, { name: "Share the Cheer", path: "/share-the-cheer" }]), { "@context": "https://schema.org", "@type": "WebPage", name: "Share the Cheer", description, url: absoluteUrl("/share-the-cheer"), about: { "@id": `${absoluteUrl("/")}#organization` } }]} />
    <section className="relative overflow-hidden bg-chestnut text-warm-white">
      <div className="absolute inset-0 opacity-30"><Image src={ASSETS.photos.hero} alt="" fill priority sizes="100vw" className="object-cover object-center" /></div>
      <div className="absolute inset-0 bg-gradient-to-r from-chestnut via-chestnut/95 to-chestnut/55" />
      <div className="relative mx-auto max-w-6xl px-4 py-20 sm:px-6 sm:py-28 lg:py-36">
        <p className="text-xs font-bold uppercase tracking-[.25em] text-accent-gold">A Christmas tradition, shared together</p>
        <h1 className="mt-4 max-w-3xl font-display text-5xl font-semibold leading-tight sm:text-6xl">Share the Cheer</h1>
        <p className="mt-6 max-w-2xl text-lg leading-relaxed text-warm-white/90 sm:text-xl">When neighbors and local businesses come together, Christmas can feel a little brighter. Chestnut & Cheer is bringing our Utah community together to create meaningful moments at home for local families facing a difficult season.</p>
        <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button href="#nominate" variant="gold">Nominate a Family</Button><Button href="#partner" variant="primary">Become a Partner</Button></div>
      </div>
    </section>

    <section className="section-pad bg-cream"><div className="mx-auto max-w-6xl px-4 sm:px-6"><SectionHeading eyebrow="The hope behind the holiday" title="A Christmas they can feel at home">We hope to create a warm, memorable experience for each selected family, shaped by the generosity of local partners.</SectionHeading>
      <div className="mt-9 grid gap-4 md:grid-cols-3">{[
        { icon: UtensilsCrossed, title: "Christmas dinner", text: "A holiday meal, ideally catered or provided by a local restaurant." },
        { icon: TreePine, title: "A real Christmas tree", text: "A fresh tree from a local farm or lot to make their home feel festive." },
        { icon: Lightbulb, title: "Outdoor holiday lights", text: "A professionally designed and installed exterior display from Chestnut & Cheer." },
      ].map(({ icon: Icon, title, text }) => <article key={title} className="rounded-3xl border border-chestnut/10 bg-white p-6 shadow-sm"><span className="inline-flex size-12 items-center justify-center rounded-full bg-accent-gold/25 text-primary-red"><Icon aria-hidden className="size-6" /></span><h3 className="mt-5 font-display text-xl font-semibold text-chestnut">{title}</h3><p className="mt-2 leading-relaxed text-chestnut/75">{text}</p></article>)}</div>
      <p className="mt-6 max-w-4xl rounded-2xl border-l-4 border-accent-gold bg-white px-5 py-4 leading-relaxed text-chestnut/85">Additional gifts, services, gift cards, experiences, and support may be added as businesses make commitments. Specific contributions and family packages depend on confirmed partner availability and cannot be guaranteed in advance.</p>
    </div></section>

    <section className="section-pad bg-white"><div className="mx-auto grid max-w-6xl gap-10 px-4 sm:px-6 lg:grid-cols-2 lg:gap-16"><div><SectionHeading eyebrow="Who it is for" title="For families carrying a lot this season">Nominations are welcome for families facing financial hardship, serious illness, the loss of a loved one, displacement, a family crisis, or another significant challenge that has made Christmas difficult.</SectionHeading><p className="mt-5 leading-relaxed text-chestnut/80">We review each story with care. Nominating someone does not guarantee selection.</p></div><div className="rounded-3xl bg-cream p-6 sm:p-8"><h3 className="font-display text-2xl font-semibold text-chestnut">A few practical requirements</h3><ul className="mt-5 space-y-3 text-chestnut/80">{["The family lives within our current service area in Utah County or Salt Lake County.", "The homeowner or property owner permits temporary lighting installation.", "The home can be safely serviced by our crew.", "The family is willing to coordinate privately with the Chestnut & Cheer office."].map((item) => <li key={item} className="flex gap-3"><span aria-hidden className="mt-1 text-primary-red">✦</span>{item}</li>)}</ul></div></div></section>

    <section className="section-pad bg-cream"><div className="mx-auto max-w-6xl px-4 sm:px-6"><SectionHeading eyebrow="How it works" title="A thoughtful plan for December">The good parts of Christmas arrive throughout the month, with time for families to enjoy them.</SectionHeading><ol className="mt-9 grid gap-4 md:grid-cols-5">{["A family is nominated.", "We review nominations privately.", `Selected families are contacted by ${selectionDate}.`, "Our office coordinates with families and participating businesses.", "Trees, lights, meals, and other confirmed gifts arrive throughout December."].map((step, i) => <li key={step} className="rounded-2xl bg-white p-5"><span className="text-sm font-bold text-primary-red">0{i + 1}</span><p className="mt-3 font-semibold leading-snug text-chestnut">{step}</p></li>)}</ol><p className="mt-6 text-sm text-chestnut/75">{SHARE_THE_CHEER.nominationOpens && SHARE_THE_CHEER.nominationCloses ? `Nominations are planned from ${SHARE_THE_CHEER.nominationOpens} through ${SHARE_THE_CHEER.nominationCloses}. ` : "Nominations are currently open; season dates will be announced when finalized. "}Our goal is to reach selected families by {selectionDate}.</p></div></section>

    <section className="section-pad bg-white"><div className="mx-auto max-w-6xl px-4 sm:px-6"><SectionHeading eyebrow="What the community can share" title="Current community needs">These are the kinds of support we are seeking. An offer becomes part of a family package only after our office confirms it.</SectionHeading><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{SHARE_THE_CHEER.needs.map((need) => <div key={need.name} className="flex items-center justify-between gap-4 rounded-2xl border border-chestnut/10 bg-cream p-4"><span className="font-medium text-chestnut">{need.name}</span><span className="shrink-0 rounded-full bg-accent-gold/30 px-3 py-1 text-xs font-semibold text-chestnut">{need.status}</span></div>)}</div></div></section>

    <section className="section-pad scroll-mt-28 bg-cream" id="nominate"><div className="mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:gap-14"><div className="lg:sticky lg:top-28 lg:self-start"><SectionHeading eyebrow="Start with a story" title="Nominate a family">A small introduction can open the door to a meaningful Christmas. Tell us about someone you care about, and we will handle the next steps with discretion.</SectionHeading><p className="mt-5 text-sm leading-relaxed text-chestnut/75">Please share only information needed for initial review. Do not send Social Security numbers, bank records, medical records, or identification documents.</p></div>{nominationsOpen() ? <CheerForm kind="nomination" /> : <p className="rounded-3xl bg-white p-8 text-chestnut">Nominations are not open right now. Please contact our office if you have a question.</p>}</div></section>

    <section className="section-pad scroll-mt-28 bg-white" id="partner"><div className="mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:gap-14"><div className="lg:sticky lg:top-28 lg:self-start"><SectionHeading eyebrow="Make room at the table" title="Become a partner">A restaurant, tree farm, shop, service team, or neighbor with something to share can help make the season feel full of possibility.</SectionHeading><p className="mt-5 leading-relaxed text-chestnut/80">Tell us what you may be able to offer. Our office will contact you to confirm the details before anything is promised to a family or recognized publicly.</p></div><CheerForm kind="partner" /></div></section>

    <section className="section-pad bg-chestnut text-warm-white"><div className="mx-auto grid max-w-6xl gap-8 px-4 sm:px-6 lg:grid-cols-[auto_1fr] lg:items-center lg:gap-12"><div className="rounded-full bg-accent-gold/15 p-5 text-accent-gold"><Heart aria-hidden className="size-12" /></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-accent-gold">Privacy and dignity</p><h2 className="mt-3 font-display text-3xl font-semibold">Every family deserves room to choose</h2><div className="mt-5 grid gap-3 text-warm-white/85 sm:grid-cols-2"><p>Families are never required to participate in publicity and may remain completely private.</p><p>Personal information is used only to review nominations and coordinate the program.</p><p>Photos and stories are shared only with clear permission from the family.</p><p>Businesses do not receive sensitive nomination details. Selection decisions are private and final.</p></div></div></div></section>

    <section className="section-pad bg-cream"><div className="mx-auto max-w-6xl px-4 sm:px-6"><SectionHeading eyebrow="Year by year" title="Annual impact">After each season, we hope to share what our community made possible, while honoring every family&apos;s privacy choices.</SectionHeading>{SHARE_THE_CHEER.recaps.length ? <div className="mt-8 space-y-3">{SHARE_THE_CHEER.recaps.map((recap) => <details key={recap.year} className="rounded-2xl border border-chestnut/10 bg-white p-5"><summary className="cursor-pointer font-display text-xl font-semibold text-chestnut">{recap.year} community recap</summary><div className="mt-4 space-y-3 text-chestnut/80"><p>{recap.familiesServed} families served · {recap.participatingBusinesses.length} participating businesses</p><p>{recap.contributions.join(", ")}</p>{recap.estimatedCommunityValue && <p>Estimated community value: {recap.estimatedCommunityValue}</p>}{recap.anonymousSummaries?.map((summary) => <p key={summary}>{summary}</p>)}{recap.approvedStories?.map((story) => <p key={story}>{story}</p>)}{recap.approvedPhotos?.map((photo) => <Image key={photo.src} src={photo.src} alt={photo.alt} width={640} height={420} loading="lazy" />)}<p>{recap.thankYou}</p></div></details>)}</div> : <div className="mt-8 rounded-3xl border border-chestnut/10 bg-white p-8"><Gift aria-hidden className="size-10 text-primary-red" /><p className="mt-4 font-display text-xl font-semibold text-chestnut">The first chapter is still being written.</p><p className="mt-2 text-chestnut/80">Our first annual recap will be published after the season, with only details, photos, and stories families have approved.</p></div>}</div></section>

    <section className="section-pad bg-white"><div className="mx-auto max-w-4xl px-4 sm:px-6"><SectionHeading eyebrow="Good to know" title="Questions about Share the Cheer" /><div className="mt-8 divide-y divide-chestnut/10 rounded-3xl border border-chestnut/10">{faq.map(([question, answer]) => <details key={question} className="group px-5 py-4 sm:px-6"><summary className="cursor-pointer list-none font-semibold text-chestnut marker:hidden">{question}<span aria-hidden className="float-right ml-4 text-primary-red">+</span></summary><p className="mt-3 max-w-3xl leading-relaxed text-chestnut/80">{answer}</p></details>)}</div></div></section>

    <section className="section-pad bg-accent-gold/25"><div className="mx-auto max-w-6xl px-4 text-center sm:px-6"><Sparkles aria-hidden className="mx-auto size-9 text-primary-red" /><h2 className="mt-4 font-display text-3xl font-semibold text-chestnut sm:text-4xl">There is room for you in this story</h2><p className="mx-auto mt-4 max-w-2xl leading-relaxed text-chestnut/80">Whether you know a family who could use a little extra light or have something to share, we would love to hear from you.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Button href="#nominate">Nominate a Family</Button><Button href="#partner" variant="outline">Offer Support</Button></div><div className="mt-8 flex flex-col items-center justify-center gap-2 text-sm text-chestnut sm:flex-row sm:gap-6"><span>Questions? Contact our office:</span><a href={LINKS.tel} className="inline-flex items-center gap-2 underline underline-offset-2"><Phone aria-hidden className="size-4" />{COMPANY.phone}</a><a href={LINKS.mailto} className="inline-flex items-center gap-2 underline underline-offset-2"><Mail aria-hidden className="size-4" />{COMPANY.email}</a></div></div></section>
  </>;
}
